name: flutter_responsive
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  # Utilize esta versão ou superior para melhor experiência.
  flutter_screenutil: ^4.0.0-beta1
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:  
  uses-material-design: true